### PR TITLE
CLI: Add the union-default-graph option to make SPARQL queries use the union of all graphs as the default graph

### PR DESCRIPTION
**Pull request by Tpt**
Issue #973

### CODE REVIEW

**Comment by ch-sander** [comment]
Wonderful. How is the CLI configured then? An environment variable?
Sorry for the basic question.

**Comment by Tpt** [comment]
Just set the `--union-default-graph` option when starting Oxigraph server

**Comment by Tpt** [comment]
@ch-sander Hey! I was not aware you were using `serve-secondary` (or of any user of it). I dropped this command from the 0.4.0-rc.1 because of all the bugs I encountered with it and RocksDB 9. Distributions have migrated to RocksDB 9 and I did not wanted to ship a badly broken feature. Can you use easily `serve` or `serve-read-only` or do you badly need it?

**Comment by ch-sander** [comment]
What is great is that a new store is target for queries immediately, so no restart of service needed. That's the main reason, I use it. But that might also be the thing to cause trouble.

It's also used by the app I run within my service: 
https://github.com/epoz/shmarql/blob/8811fddb8f7f4b104e504437564616cd2f290776/src/app/main.py#L73-L84

Maybe there's a work-around for both cases? I guess the shmarql exception handling could also just fall back to `read_only` @epoz ?

**Comment by Tpt** [comment]
@ch-sander If I understand your code correctly, you are loading some data into Oxigraph when starting the script and then only do read-only access. If yes, I see two approaches:
- if you only have a few triples (less than a million) I would just load the data into memory each time you start the script, maybe with a on-disk cache for the data you load from the web.
- if you have more triples what you can do is that the first process open the store as read/write, load the file and then create a file with a well known name. The other processes would just wait with a sleep loop for this file to exist before opening the store as read only. Idea:
```python
try:
    GRAPH = px.Store(STORE_PATH)
    # Do loading ....
   with open(MY_WELL_KNOWN_FILE, "wt") as fp:
       fp.write(" ") # Create the file
except OSError:
   while not os.path.exists(MY_WELL_KNOWN_FILE):
      sleep(1)
  GRAPH = px.store.read_only(STORE_PATH)
```
I hope it helps and that I have understood your use-case well

**Comment by ch-sander** [comment]
Thanks, but the code is @epoz 's -- my use case is much simpler: I load triples into the store with pyoxigraph (similar to shamrql) but with oxigraph server, running on its own, and having set the location to this store fed by pyoxigraph, I want to have this data ready for a query without restarting oxigraph server. You suggested the serve-secondary solution, I guess, here: https://github.com/oxigraph/oxigraph/issues/948#issuecomment-2262205513

Can the server be triggered to realod the store from location without restart and http only?

**Comment by Tpt** [comment]
@ch-sander Thank you for the context. I missed it. Sadly a reload from location cannot be triggered without a restart (this kind of reload without secondary system would be in fact more or less a restart). If you don't have too many data, the easiest way is maybe to send the extra data to the HTTP server as RDF files or SPARQL updates.

To add graph data to the default graph: `curl -X POST -H "content-type: text/turtle" http://localhost:7878/store?default`
To add dataset data: `curl -X POST -H "content-type: application/trig" http://localhost:7878/store`
To add graph data to a named graph: `curl -X POST -H "content-type: text-turtle" http://localhost:7878/store?graph=http://example.com`

Add `?no_transaction&lenient` if you want faster loading to disable transactional updates and most data validations.

**Comment by ch-sander** [comment]
I will have to find a way. The files are/will be c. 500mb in ttl. I think I remember `/store` can also load from remote. And I understand uploads via `/store` will work also if the server is run `serve-read-only`, right? Or would I need to `serve` and have a nginx (or other proxy) config to virtually disallow access to `store`?

**Comment by Tpt** [comment]
> The files are/will be c. 500mb in ttl.

It should be fine via `/store`. If you set the `no_transaction` option, parsing and loading will be streamed so memory consumption should be ok.

> I think I remember /store can also load from remote.

You can indeed run SPARQL UPDATE `LOAD` command.

> And I understand uploads via /store will work also if the server is run serve-read-only, right?

Sadly not. You need a read/write server via the `serve` option and a proxy.

A quick and dirty approach might be to still do the loading via pyoxigraph or something similar and restart the read-only server when needed. The restart operation should be fast (less than a second).

**Comment by ch-sander** [comment]
Thanks, will do so. The updates will occur quite regularly, the restart time is not the issue, but it safely needs to be triggered from remote via http. I need to find a good solution. 

Previously the pyoxigraph was part of fastapi app behind http authentication on a VM with a store directory mounted to another VM with Oxigraph server served secondary from the mount.

**Comment by Tpt** [comment]
Quick thought: to avoid to have two Oxigraph processes, you might write in fastapi an implementation of the [SPARQL HTTP protocol]([http://www.w3.org/TR/sparql11-protocol/](https://www.w3.org/TR/sparql11-protocol/) to serve SPARQL queries from the same app. Implementing it only for queries should not be very hard.

**Comment by ch-sander** [comment]
It's wonderful to have you reflecting on my use case, especially as I'm a beginner.

The shmarql app (fastapi) that runs beneath my own app to ingest RDF files into the `/store` via http has already an oxigraph-based SPARQL endpoint. I could well integrate this as endpoint for ResearchSpace, but I thought the "actual" oxigraph server is better maintained and more stable for production. E.g., shmarql does not support the flags for union-default or graph-uri (can be done easily, I know).

But with all these options, I will find a solution that fits and this without oxigraph having a buggy feature such as `serve-secondary`. If you ever resurrect it, maybe send me a note (and I will check the CHANGELOG).

**Comment by Tpt** [comment]
Thank you for the nice reply!

The SPARQL protocol is quite stable and fastapi is very well maintained and stable so I tend to think it might be as good as Oxigraph http server on the stability side.

I will ping you if I resurect `serve-secondary`!

**Pull request merged**
