### PR TITLE
CI: Attempt to cache Cargo cache

### PR DESCRIPTION
**Pull request by Tpt**

### CODE REVIEW

**Comment by adamreichold** [comment]
I think you might see much better results using https://github.com/Swatinem/rust-cache

**Comment by Tpt** [comment]
> I think you might see much better results using https://github.com/Swatinem/rust-cache

Thank you! Sadly a huge chuck of the compile time is caused by RocksDB that is included in Oxigraph Cargo workspace so I am not sure it's going to help because Swatinem/rust-cache won't cache it.

**Comment by adamreichold** [comment]
> > I think you might see much better results using https://github.com/Swatinem/rust-cache
> 
> Thank you! Sadly a huge chuck of the compile time is caused by RocksDB that is included in Oxigraph Cargo workspace so I am not sure it's going to help because Swatinem/rust-cache won't cache it.

Couldn't you just put `oxrocksdb-sys` into a separate workspace by adding an empty `[workspace]` table to its `Cargo.toml`? You should still be able to use it as a path dependency. The only downside I see is that you will get a separate target directory when you work on the bindings themselves.

**Comment by Tpt** [comment]
> Couldn't you just put oxrocksdb-sys into a separate workspace by adding an empty [workspace] table to its Cargo.toml? You should still be able to use it as a path dependency. The only downside I see is that you will get a separate target directory when you work on the bindings themselves.

That's a great idea! Thank you!

**Pull request merged**
